import type { LifeArea, VedicChart } from "./vedic-engine";

export type GuideLanguage = "en" | "si";
export type GuidanceCard = { key:string; title:string; level:string; paragraph:string; action:string; caution:string; evidence:string[] };

const AREAS: Record<string, { en:{focus:string;strength:string;challenge:string;action:string;caution:string}; si:{focus:string;strength:string;challenge:string;action:string;caution:string} }> = {
  identity:{en:{focus:"your confidence, decisions and overall direction",strength:"You can develop a clear personal direction and rebuild confidence after uncertain periods",challenge:"outside expectations may sometimes make you question your own path",action:"Choose a few meaningful priorities and decide from your long-term values",caution:"Do not compare your timing too closely with other people"},si:{focus:"ඔබේ ආත්මවිශ්වාසය, තීරණ සහ ජීවන දිශාව",strength:"අවිශ්වාස කාලයකින් පසුව වුවද පැහැදිලි දිශාවක් සහ ආත්මවිශ්වාසයක් නැවත ගොඩනඟා ගත හැක",challenge:"අන් අයගේ අපේක්ෂා නිසා සමහරවිට ඔබේ මාර්ගය ගැන සැකයක් ඇති විය හැක",action:"වැදගත් දිගුකාලීන අරමුණු කිහිපයක් තෝරා ඒවාට අනුව තීරණ ගන්න",caution:"ඔබේ ප්‍රගතිය අන් අය සමඟ අධිකව සසඳන්න එපා"}},
  career:{en:{focus:"work, leadership, responsibility and recognition",strength:"You can grow through responsibility, practical experience and work that gives you room to decide",challenge:"recognition may not always arrive as quickly as your effort deserves",action:"Build specialist knowledge, record your results and follow one clear direction",caution:"Avoid leaving a promising path only because early progress feels slow"},si:{focus:"රැකියාව, නායකත්වය, වගකීම් සහ පිළිගැනීම",strength:"වගකීම්, ප්‍රායෝගික අත්දැකීම් සහ තීරණ ගැනීමට ඉඩ ඇති වැඩ තුළින් වර්ධනය විය හැක",challenge:"ඔබේ උත්සාහයට සරිලන පිළිගැනීම සෑමවිටම ඉක්මනින් නොලැබිය හැක",action:"විශේෂඥ දැනුම ගොඩනඟා, ප්‍රතිඵල සටහන් කර, පැහැදිලි වෘත්තීය දිශාවක් අනුගමනය කරන්න",caution:"මුල් ප්‍රගතිය මන්දගාමී නිසා හොඳ මාර්ගයක් අත්හරින්න එපා"}},
  wealth:{en:{focus:"income, savings, assets and opportunities",strength:"You can improve stability by combining practical planning with more than one useful source of value",challenge:"income and expenses may move in cycles when decisions are made under pressure",action:"Keep reserves, separate long-term assets from daily cash and review decisions calmly",caution:"Avoid emotional spending, unclear partnerships and relying on income before it arrives"},si:{focus:"ආදායම, ඉතිරිකිරීම්, වත්කම් සහ අවස්ථා",strength:"ප්‍රායෝගික සැලසුම් සහ වටිනාකම් සපයන මාර්ග කිහිපයක් එක් කිරීමෙන් ස්ථාවරත්වය වර්ධනය කළ හැක",challenge:"පීඩනය යටතේ තීරණ ගන්නා විට ආදායම් සහ වියදම් චක්‍රාකාර විය හැක",action:"හදිසි අරමුදලක් තබා, දිගුකාලීන වත්කම් දෛනික මුදල්වලින් වෙන් කර, තීරණ සන්සුන්ව සමාලෝචනය කරන්න",caution:"හැඟීම් මත වියදම්, අපැහැදිලි හවුල්කාරිත්ව සහ ලැබීමට පෙර ආදායම මත රඳා සිටීමෙන් වළකින්න"}},
  relationships:{en:{focus:"marriage, close partnerships, trust and emotional exchange",strength:"You can be loyal and protective once trust and mutual respect are established",challenge:"unspoken expectations or carrying too much responsibility can create distance",action:"Discuss needs early, maintain fair boundaries and make important decisions together",caution:"Do not keep disappointment hidden until it becomes resentment"},si:{focus:"විවාහය, සමීප සබඳතා, විශ්වාසය සහ හැඟීම් හුවමාරුව",strength:"විශ්වාසය සහ ගෞරවය ඇති විට විශ්වාසවන්ත සහ ආරක්ෂාකාරී සහකරුවෙකු විය හැක",challenge:"නොකියූ අපේක්ෂා හෝ අධික වගකීම් මානසික දුරස්ථභාවයක් ඇති කළ හැක",action:"අවශ්‍යතා කලින් කතා කර, සාධාරණ සීමා තබා, වැදගත් තීරණ එකට ගන්න",caution:"අසතුට කෝපයක් වන තුරු සඟවා තබන්න එපා"}},
  home:{en:{focus:"home, family responsibilities, property and inner security",strength:"You can create a dependable home base and gradually build lasting security",challenge:"family duties or property matters may sometimes feel heavier than expected",action:"Create clear family roles and approach property decisions with patient planning",caution:"Avoid carrying every family problem alone"},si:{focus:"නිවස, පවුල් වගකීම්, දේපළ සහ අභ්‍යන්තර ආරක්ෂාව",strength:"විශ්වාසදායක ගෘහ පදනමක් සාදා දිගුකාලීන ආරක්ෂාව ක්‍රමයෙන් ගොඩනඟා ගත හැක",challenge:"පවුල් වගකීම් හෝ දේපළ කාරණා සමහරවිට අපේක්ෂාවට වඩා බර විය හැක",action:"පවුලේ වගකීම් පැහැදිලි කර දේපළ තීරණ ඉවසීමෙන් සැලසුම් කරන්න",caution:"සෑම පවුල් ගැටලුවක්ම තනිව භාරගන්න එපා"}},
  health:{en:{focus:"energy, daily habits, recovery and resilience",strength:"A steady routine can improve your energy and ability to recover from demanding periods",challenge:"stress may build quietly when rest is postponed for responsibilities",action:"Protect sleep, movement, regular meals and time away from constant work",caution:"Do not ignore persistent symptoms or replace professional care with astrology"},si:{focus:"ශක්තිය, දෛනික පුරුදු, සුවය සහ ඔරොත්තු දීම",strength:"ස්ථාවර දිනචරියාවක් ශක්තිය සහ පීඩාකාරී කාලවලින් සුවය ලැබීමේ හැකියාව වැඩි කරයි",challenge:"වගකීම් නිසා විවේකය කල් දමන විට පීඩනය නොදැනීමෙන් සමුච්චය විය හැක",action:"නින්ද, චලනය, නිසි ආහාර සහ වැඩෙන් වෙන් වූ කාලය ආරක්ෂා කරන්න",caution:"දිගටම පවතින ලක්ෂණ නොසලකා හරින්න හෝ වෛද්‍ය උපදෙස් වෙනුවට ජ්‍යෝතිෂය භාවිත කරන්න එපා"}},
  learning:{en:{focus:"learning, communication, creativity and judgment",strength:"You can learn effectively through practical use, observation and explaining ideas to others",challenge:"too many interests at once can divide attention and delay mastery",action:"Choose one important subject at a time and turn learning into a real project",caution:"Avoid collecting information without applying it"},si:{focus:"ඉගෙනීම, සන්නිවේදනය, නිර්මාණශීලීත්වය සහ විනිශ්චය",strength:"ප්‍රායෝගික භාවිතය, නිරීක්ෂණය සහ අන් අයට පැහැදිලි කිරීම තුළින් හොඳින් ඉගෙන ගත හැක",challenge:"එකවර උනන්දුවීම් වැඩිවීම අවධානය බෙදා ප්‍රවීණත්වය ප්‍රමාද කළ හැක",action:"වරකට වැදගත් විෂයක් තෝරා ඉගෙනීම සැබෑ ව්‍යාපෘතියක් බවට පත් කරන්න",caution:"දැනුම ක්‍රියාවට නොගෙන තොරතුරු පමණක් රැස් කිරීමෙන් වළකින්න"}},
  spiritual:{en:{focus:"inner growth, meaning, intuition and unfamiliar experiences",strength:"Reflection can give you insight and help redirect life with greater purpose",challenge:"withdrawal may occur when worldly results do not match inner expectations",action:"Keep a reflective practice while remaining involved in practical responsibilities",caution:"Avoid using detachment to escape necessary decisions"},si:{focus:"අභ්‍යන්තර වර්ධනය, අර්ථය, අනුභූතිය සහ නව අත්දැකීම්",strength:"සන්සුන්ව සිතා බැලීම ඔබට ගැඹුරු අවබෝධයක් ලබාදී ජීවිතය අර්ථවත් දිශාවකට යොමු කරයි",challenge:"ලෞකික ප්‍රතිඵල අභ්‍යන්තර අපේක්ෂාවට නොගැළපෙන විට ඉවත් වීමක් ඇති විය හැක",action:"ප්‍රායෝගික වගකීම්වල නිරතව සිටින අතරම සිතා බැලීමේ පුරුද්දක් තබාගන්න",caution:"අවශ්‍ය තීරණවලින් පලා යාමට විරාගය හේතුවක් කරගන්න එපා"}},
};

function label(score:number, language:GuideLanguage) {
  if (language === "si") return score >= 80 ? "ප්‍රධාන ශක්තිය" : score >= 65 ? "ශක්තිමත් හැකියාව" : score >= 50 ? "වර්ධනය වන අංශය" : score >= 35 ? "සැලකිලිමත් උත්සාහය අවශ්‍යයි" : "ප්‍රධාන ජීවන පාඩම";
  return score >= 80 ? "Major strength" : score >= 65 ? "Strong potential" : score >= 50 ? "Developing area" : score >= 35 ? "Needs conscious effort" : "Major life lesson";
}

function compose(area:LifeArea, language:GuideLanguage, seed:number):GuidanceCard {
  const text=AREAS[area.key][language];
  const openingsEn=["A central theme here is","Your chart places meaningful emphasis on","Over time, you may become more conscious of"];
  const openingsSi=["මෙම අංශයේ ප්‍රධාන තේමාව වන්නේ","ඔබේ ජන්ම පත්‍රය විශේෂ අවධානයක් යොමු කරන්නේ","කාලයත් සමඟ ඔබ වැඩි අවධානයක් යොමු කිරීමට ඉඩ ඇත්තේ"];
  const linksEn=["At its best,","When used constructively,","With conscious effort,"];
  const linksSi=["හොඳින් භාවිත කළ විට","ධනාත්මකව මෙහෙයවූ විට","සැලකිලිමත් උත්සාහයකින්"];
  const paragraph=language==="si"?`${openingsSi[seed%3]} ${text.focus} ය. ${linksSi[(seed+1)%3]} ${text.strength}. එහෙත් ${text.challenge}. එබැවින් ඉක්මන් නිගමනවලට වඩා ස්ථාවර සහ සවිඥානික ක්‍රියාවලියක් හොඳම ප්‍රතිඵල ලබාදෙයි.`:`${openingsEn[seed%3]} ${text.focus}. ${linksEn[(seed+1)%3]} ${text.strength}. However, ${text.challenge}. The best results come from a steady, conscious approach rather than quick conclusions.`;
  return {key:area.key,title:language==="si"?area.titleSi:area.titleEn,level:label(area.score,language),paragraph,action:text.action,caution:text.caution,evidence:language==="si"?area.factorsSi:area.factorsEn};
}

export function buildLifeGuide(chart:VedicChart, language:GuideLanguage) {
  const cards=chart.lifeAreas.map((area,index)=>compose(area,language,area.score+chart.ascendant.signIndex*7+index*11));
  const ranked=[...chart.lifeAreas].sort((a,b)=>b.score-a.score); const title=(area:LifeArea)=>language==="si"?area.titleSi:area.titleEn;
  const maha=language==="si"?chart.dasha.currentMaha?.lordSi:chart.dasha.currentMaha?.lordEn; const antar=language==="si"?chart.dasha.currentAntar?.lordSi:chart.dasha.currentAntar?.lordEn;
  return {cards,strengths:ranked.slice(0,3).map(title),growth:ranked.slice(-2).reverse().map(title),timing:language==="si"?`දැනට ${maha||"-"} මහා දශාව සහ ${antar||"-"} අතුරු දශාව ක්‍රියාත්මක වේ. මෙම ග්‍රහයන්ට අදාළ ජීවන අංශ වැඩි අවධානයක් ඉල්ලා සිටිය හැක.`:`The current ${maha||"-"} mahadasha and ${antar||"-"} antardasha make their related life themes more active. Treat this as guidance for conscious choices, not a fixed prediction.`,overall:language==="si"?"ඔබේ ජන්ම පත්‍රයේ ශක්තිමත් සහ අභියෝගාත්මක සාධක දෙකම ඇත. ප්‍රධාන මඟපෙන්වීම වන්නේ ස්වභාවික ශක්තීන් භාවිත කරමින් වැඩි උත්සාහයක් අවශ්‍ය අංශ ක්‍රමයෙන් ශක්තිමත් කිරීමයි.":"Your chart contains both supportive and demanding factors. The central guidance is to use your natural strengths while steadily developing the areas that require more conscious effort."};
}
