import type { ChartPlanet, VedicChart } from "./vedic-engine";

type IndustryRule={key:string;en:string;si:string;planets:string[];houses:number[];rolesEn:string[];rolesSi:string[]};
const INDUSTRIES:IndustryRule[]=[
 {key:"hospitality",en:"Hospitality, hotels & guest services",si:"ආගන්තුක සත්කාර, හෝටල් සහ අමුත්තන් සේවා",planets:["moon","venus","mercury","jupiter"],houses:[4,7,10,11],rolesEn:["hotel operations","revenue and OTA management","guest-experience leadership","hospitality consulting"],rolesSi:["හෝටල් මෙහෙයුම්","ආදායම් සහ OTA කළමනාකරණය","අමුත්තන් අත්දැකීම් නායකත්වය","ආගන්තුක සත්කාර උපදේශනය"]},
 {key:"travel",en:"Travel, tourism & international services",si:"සංචාරක, සංචාර සහ ජාත්‍යන්තර සේවා",planets:["moon","venus","rahu","jupiter"],houses:[7,9,10,12],rolesEn:["travel coordination","destination services","international customer operations","tourism business development"],rolesSi:["සංචාර සම්බන්ධීකරණය","ගමනාන්ත සේවා","ජාත්‍යන්තර පාරිභෝගික මෙහෙයුම්","සංචාරක ව්‍යාපාර සංවර්ධනය"]},
 {key:"technology",en:"Technology, digital platforms & systems",si:"තාක්ෂණය, ඩිජිටල් වේදිකා සහ පද්ධති",planets:["mercury","rahu","saturn"],houses:[3,6,10,11],rolesEn:["product operations","software-enabled services","digital systems management","technology consulting"],rolesSi:["නිෂ්පාදන මෙහෙයුම්","මෘදුකාංග-සහිත සේවා","ඩිජිටල් පද්ධති කළමනාකරණය","තාක්ෂණ උපදේශනය"]},
 {key:"finance",en:"Finance, commerce & asset management",si:"මූල්‍ය, වෙළඳාම සහ වත්කම් කළමනාකරණය",planets:["mercury","jupiter","venus"],houses:[2,8,10,11],rolesEn:["commercial management","financial planning","portfolio administration","business analysis"],rolesSi:["වාණිජ කළමනාකරණය","මූල්‍ය සැලසුම්","ආයෝජන පරිපාලනය","ව්‍යාපාර විශ්ලේෂණය"]},
 {key:"education",en:"Education, training & advisory work",si:"අධ්‍යාපනය, පුහුණුව සහ උපදේශන සේවා",planets:["jupiter","mercury","sun"],houses:[5,9,10,11],rolesEn:["training","consulting","knowledge products","institutional leadership"],rolesSi:["පුහුණුව","උපදේශනය","දැනුම් නිෂ්පාදන","ආයතනික නායකත්වය"]},
 {key:"healthcare",en:"Healthcare, wellbeing & care services",si:"සෞඛ්‍ය, සුවතා සහ සැලකිලි සේවා",planets:["moon","jupiter","mars"],houses:[6,8,10,12],rolesEn:["care coordination","health operations","wellbeing services","service administration"],rolesSi:["සැලකිලි සම්බන්ධීකරණය","සෞඛ්‍ය මෙහෙයුම්","සුවතා සේවා","සේවා පරිපාලනය"]},
 {key:"government",en:"Government, administration & public leadership",si:"රාජ්‍ය, පරිපාලන සහ මහජන නායකත්වය",planets:["sun","jupiter","saturn"],houses:[6,9,10,11],rolesEn:["administration","policy operations","public-service management","institutional leadership"],rolesSi:["පරිපාලනය","ප්‍රතිපත්ති මෙහෙයුම්","රාජ්‍ය සේවා කළමනාකරණය","ආයතනික නායකත්වය"]},
 {key:"engineering",en:"Engineering, construction & technical operations",si:"ඉංජිනේරු, ඉදිකිරීම් සහ තාක්ෂණික මෙහෙයුම්",planets:["mars","saturn","mercury"],houses:[3,6,10,11],rolesEn:["technical operations","project delivery","engineering coordination","quality systems"],rolesSi:["තාක්ෂණික මෙහෙයුම්","ව්‍යාපෘති ක්‍රියාත්මක කිරීම","ඉංජිනේරු සම්බන්ධීකරණය","තත්ත්ව පද්ධති"]},
 {key:"creative",en:"Creative, design, media & luxury services",si:"නිර්මාණ, සැලසුම්, මාධ්‍ය සහ සුඛෝපභෝගී සේවා",planets:["venus","moon","mercury"],houses:[3,5,7,10],rolesEn:["brand direction","design services","content strategy","creative business"],rolesSi:["සන්නාම දිශානතිය","සැලසුම් සේවා","අන්තර්ගත උපායමාර්ග","නිර්මාණ ව්‍යාපාර"]},
 {key:"sales",en:"Sales, marketing & business development",si:"විකුණුම්, අලෙවිකරණ සහ ව්‍යාපාර සංවර්ධනය",planets:["mercury","mars","rahu"],houses:[3,7,10,11],rolesEn:["business development","account leadership","digital marketing","commercial partnerships"],rolesSi:["ව්‍යාපාර සංවර්ධනය","ගිණුම් නායකත්වය","ඩිජිටල් අලෙවිකරණය","වාණිජ හවුල්කාරිත්වය"]},
 {key:"law",en:"Law, compliance & governance",si:"නීතිය, අනුකූලතාව සහ පාලනය",planets:["jupiter","sun","saturn"],houses:[6,8,9,10],rolesEn:["compliance","governance","contract administration","advisory work"],rolesSi:["අනුකූලතාව","පාලනය","ගිවිසුම් පරිපාලනය","උපදේශන සේවා"]},
 {key:"agriculture",en:"Agriculture, property & land-based enterprise",si:"කෘෂිකර්ම, දේපළ සහ ඉඩම්-මූලික ව්‍යාපාර",planets:["moon","mars","saturn"],houses:[2,4,10,11],rolesEn:["property operations","agri-business","estate management","supply coordination"],rolesSi:["දේපළ මෙහෙයුම්","කෘෂි ව්‍යාපාර","වතු කළමනාකරණය","සැපයුම් සම්බන්ධීකරණය"]},
];
const byKey=(chart:VedicChart,key:string)=>chart.planets.find(p=>p.key===key)!;
const effective=(p:ChartPlanet)=>p.strength+(p.dignity==="exalted"?8:p.dignity==="own"?5:p.dignity==="debilitated"?-8:0)-(p.combust?7:0);

export function buildHolisticSignals(chart:VedicChart){
 const raw=INDUSTRIES.map(rule=>{const planetPower=rule.planets.reduce((sum,key)=>sum+effective(byKey(chart,key)),0)/rule.planets.length;const housePower=rule.houses.reduce((sum,h)=>sum+chart.houses[h-1].score,0)/rule.houses.length;const occupants=chart.planets.filter(p=>rule.houses.includes(p.house)&&rule.planets.includes(p.key)).length*4;const yogaBoost=chart.yogas.reduce((sum,y)=>y.planets.some(name=>rule.planets.some(key=>byKey(chart,key).nameEn===name))?sum+y.power/45:sum,0);return {rule,raw:planetPower*.48+housePower*.42+occupants+yogaBoost};});
 const min=Math.min(...raw.map(x=>x.raw)),max=Math.max(...raw.map(x=>x.raw));
 const industries=raw.map(({rule,raw:score})=>({key:rule.key,nameEn:rule.en,nameSi:rule.si,score:Math.round(max===min?65:40+((score-min)/(max-min))*52),rolesEn:rule.rolesEn,rolesSi:rule.rolesSi})).sort((a,b)=>b.score-a.score);
 const h=(n:number)=>chart.houses[n-1].score,p=(k:string)=>effective(byKey(chart,k));
 const enterprise=Math.round(Math.max(20,Math.min(95,h(7)*.35+h(3)*.2+h(10)*.2+p("mars")*.1+p("mercury")*.15)));
 const employment=Math.round(Math.max(20,Math.min(95,h(6)*.42+h(10)*.33+p("saturn")*.15+p("sun")*.1)));
 const international=Math.round(Math.max(20,Math.min(95,h(9)*.28+h(12)*.32+p("rahu")*.25+p("jupiter")*.15)));
 const leadership=Math.round(Math.max(20,Math.min(95,h(1)*.25+h(10)*.35+p("sun")*.22+p("mars")*.08+p("jupiter")*.1)));
 return {industries,workStyle:{enterprise,employment,international,leadership},dominantPlanets:[...chart.planets].sort((a,b)=>effective(b)-effective(a)).slice(0,4).map(p=>({name:p.nameEn,strength:p.strength,house:p.house,dignity:p.dignity})),strongestHouses:[...chart.houses].sort((a,b)=>b.score-a.score).slice(0,4).map(house=>({house:house.house,score:house.score,lord:house.lordEn,lordHouse:house.lordHouse})),currentDasha:{maha:chart.dasha.currentMaha?.lordEn,antar:chart.dasha.currentAntar?.lordEn,pratyantar:chart.dasha.currentPratyantar?.lordEn}};
}
