import type { ChartPlanet, ChartYoga, VedicChart } from "./vedic-engine";

type Language = "en" | "si";
type Meaning = { en:string; si:string; giftEn:string; giftSi:string; riskEn:string; riskSi:string; actionEn:string; actionSi:string };

const P: Record<string, Meaning> = {
 sun:{en:"identity, confidence, leadership and recognition",si:"අනන්‍යතාව, ආත්මවිශ්වාසය, නායකත්වය සහ පිළිගැනීම",giftEn:"act with purpose and take responsible leadership",giftSi:"අරමුණක් ඇතිව ක්‍රියා කර වගකීම් සහිත නායකත්වය ගන්න",riskEn:"pride, approval-seeking or conflict with authority",riskSi:"අහංකාරය, පිළිගැනීම සෙවීම හෝ අධිකාරිය සමඟ ගැටුම්",actionEn:"Lead clearly while listening to other people",actionSi:"අන් අයට සවන් දෙමින් පැහැදිලිව නායකත්වය ගන්න"},
 moon:{en:"emotions, habits, care, memory and inner security",si:"හැඟීම්, පුරුදු, සැලකිල්ල, මතකය සහ අභ්‍යන්තර ආරක්ෂාව",giftEn:"understand people and adapt sensitively",giftSi:"මිනිසුන් තේරුම්ගෙන සංවේදීව අනුවර්තනය වන්න",riskEn:"mood changes, worry or absorbing other people's feelings",riskSi:"මනෝභාව වෙනස්වීම්, කනස්සල්ල හෝ අන් අයගේ හැඟීම් තමන්ට ගැනීම",actionEn:"Protect sleep, routine and emotional boundaries",actionSi:"නින්ද, දෛනික රටාව සහ මානසික සීමා ආරක්ෂා කරන්න"},
 mercury:{en:"thinking, learning, speech, business and decisions",si:"සිතීම, ඉගෙනීම, කථනය, ව්‍යාපාර සහ තීරණ",giftEn:"learn quickly, communicate and solve practical problems",giftSi:"වේගයෙන් ඉගෙනගෙන සන්නිවේදනය කර ප්‍රායෝගික ගැටලු විසඳන්න",riskEn:"overthinking, nervous haste or changing decisions too often",riskSi:"අධිකව සිතීම, කලබලයෙන් ඉක්මන් වීම හෝ නිතර තීරණ වෙනස් කිරීම",actionEn:"Write important decisions down and verify the facts",actionSi:"වැදගත් තීරණ ලියා තබා කරුණු තහවුරු කරන්න"},
 venus:{en:"relationships, values, comfort, creativity and agreement",si:"සබඳතා, වටිනාකම්, සුවපහසුව, නිර්මාණශීලීත්වය සහ එකඟතාව",giftEn:"create harmony, beauty and cooperative relationships",giftSi:"සමගිය, සුන්දරත්වය සහ සහයෝගී සබඳතා ගොඩනඟන්න",riskEn:"over-attachment, indulgence or avoiding necessary conflict",riskSi:"අධික බැඳීම, සීමාව ඉක්මවා වින්දනය හෝ අවශ්‍ය ගැටුම මගහැරීම",actionEn:"Keep affection, money and personal boundaries balanced",actionSi:"ආදරය, මුදල් සහ පුද්ගලික සීමා සමබරව තබන්න"},
 mars:{en:"drive, courage, competition, action and conflict",si:"ක්‍රියාශීලීත්වය, ධෛර්යය, තරඟය, ක්‍රියාව සහ ගැටුම",giftEn:"act decisively and protect what matters",giftSi:"තීරණාත්මකව ක්‍රියා කර වැදගත් දේ ආරක්ෂා කරන්න",riskEn:"impatience, anger, accidents or unnecessary confrontation",riskSi:"ඉවසිල්ල අඩුවීම, කෝපය, අනතුරු හෝ අනවශ්‍ය ගැටුම්",actionEn:"Use physical activity and pause before reacting",actionSi:"ශාරීරික ක්‍රියාකාරකම් භාවිත කර ප්‍රතිචාරයට පෙර මොහොතක් නවතින්න"},
 jupiter:{en:"wisdom, growth, teaching, ethics and opportunity",si:"ප්‍රඥාව, වර්ධනය, ඉගැන්වීම, ධර්මය සහ අවස්ථා",giftEn:"see the larger picture and guide others constructively",giftSi:"විශාල පින්තූරය දැක අන් අයට නිර්මාණාත්මක මඟපෙන්වීමක් දෙන්න",riskEn:"overconfidence, excess or promising more than is practical",riskSi:"අධික විශ්වාසය, සීමාව ඉක්මවීම හෝ කළ හැකි දේට වඩා පොරොන්දු වීම",actionEn:"Combine optimism with evidence and measured expansion",actionSi:"ශුභවාදය සාක්ෂි සහ පියවරෙන් පියවර වර්ධනය සමඟ එක් කරන්න"},
 saturn:{en:"discipline, duty, delay, endurance and long-term results",si:"විනය, වගකීම, ප්‍රමාදය, ඉවසීම සහ දිගුකාලීන ප්‍රතිඵල",giftEn:"build durable results through patience and consistency",giftSi:"ඉවසීම සහ අඛණ්ඩතාවයෙන් ස්ථාවර ප්‍රතිඵල ගොඩනඟන්න",riskEn:"fear, isolation, heaviness or carrying too much alone",riskSi:"බිය, හුදකලාව, බරපතළ බව හෝ සියල්ල තනිව දරා ගැනීම",actionEn:"Use routines, realistic timelines and shared responsibility",actionSi:"දෛනික රටා, යථාර්ථ කාලසීමා සහ බෙදාගත් වගකීම් භාවිත කරන්න"},
 rahu:{en:"ambition, unfamiliar paths, amplification and worldly desire",si:"අභිලාෂය, නව මාර්ග, විශාල කිරීම සහ ලෞකික ආශාව",giftEn:"cross boundaries, innovate and pursue unusual opportunities",giftSi:"සීමා ඉක්මවා නවෝත්පාදනය කර අසාමාන්‍ය අවස්ථා සොයන්න",riskEn:"obsession, confusion, shortcuts or never feeling satisfied",riskSi:"අධික ඇලීම, අවුල් බව, කෙටි මාර්ග හෝ කිසිදා තෘප්තිමත් නොවීම",actionEn:"Check motives, facts and consequences before a major leap",actionSi:"විශාල පියවරකට පෙර අරමුණ, කරුණු සහ ප්‍රතිවිපාක පරීක්ෂා කරන්න"},
 ketu:{en:"detachment, insight, past mastery and inner searching",si:"විරාගය, අභ්‍යන්තර දෘෂ්ටිය, පෙර හුරුබුහුටි බව සහ අර්ථ සෙවීම",giftEn:"see beneath appearances and simplify what is unnecessary",giftSi:"පෙනුමට යටින් ඇති දේ දැක අනවශ්‍ය දේ සරල කරන්න",riskEn:"withdrawal, doubt, sudden disinterest or losing practical focus",riskSi:"ඉවත් වීම, සැකය, හදිසි උනන්දුව අඩුවීම හෝ ප්‍රායෝගික අවධානය නැතිවීම",actionEn:"Keep spiritual insight connected to practical commitments",actionSi:"අභ්‍යන්තර අවබෝධය ප්‍රායෝගික වගකීම් සමඟ සම්බන්ධ කර තබන්න"},
};

type YogaMeaning={lifeEn:string;lifeSi:string;giftEn:string;giftSi:string;riskEn:string;riskSi:string;actionEn:string;actionSi:string};
const Y:Record<string,YogaMeaning>={
 "gaja-kesari":{lifeEn:"judgement, reputation and supporting others",lifeSi:"විනිශ්චය, කීර්තිය සහ අන් අයට සහාය දීම",giftEn:"balanced intelligence and respected guidance",giftSi:"සමබර බුද්ධිය සහ ගෞරවනීය මඟපෙන්වීම",riskEn:"expecting respect without continued effort",riskSi:"අඛණ්ඩ උත්සාහයකින් තොරව ගෞරවය බලාපොරොත්තු වීම",actionEn:"Use knowledge in service, teaching or responsible decisions",actionSi:"දැනුම සේවය, ඉගැන්වීම හෝ වගකීම් සහිත තීරණ සඳහා යොදාගන්න"},
 "budha-aditya":{lifeEn:"intellect, communication, planning and administration",lifeSi:"බුද්ධිය, සන්නිවේදනය, සැලසුම් සහ පරිපාලනය",giftEn:"clear analysis and persuasive expression",giftSi:"පැහැදිලි විශ්ලේෂණය සහ බලපෑම් සහිත ප්‍රකාශනය",riskEn:"mental pride or speaking before listening",riskSi:"බුද්ධිමය අහංකාරය හෝ සවන් දීමට පෙර කතා කිරීම",actionEn:"Use communication to clarify, not dominate",actionSi:"පාලනය කිරීමට නොව පැහැදිලි කිරීමට සන්නිවේදනය භාවිත කරන්න"},
 "chandra-mangala":{lifeEn:"initiative, enterprise, money activity and emotional drive",lifeSi:"ආරම්භක ශක්තිය, ව්‍යාපාරික බව, මුදල් ක්‍රියාකාරකම් සහ හැඟීම්මය උද්දීපනය",giftEn:"commercial initiative and courage to act",giftSi:"ව්‍යාපාරික ආරම්භක ශක්තිය සහ ක්‍රියා කිරීමට ධෛර්යය",riskEn:"emotion-driven financial or relationship decisions",riskSi:"හැඟීම් මත ගන්නා මුදල් හෝ සබඳතා තීරණ",actionEn:"Pause before spending, investing or confronting",actionSi:"වියදම්, ආයෝජන හෝ ගැටුම්වලට පෙර නවතින්න"},
 kemadruma:{lifeEn:"emotional self-reliance and periods of inner isolation",lifeSi:"මානසික ස්වයංනිර්භරතාව සහ අභ්‍යන්තර හුදකලා කාල",giftEn:"independence and deep self-awareness",giftSi:"ස්වාධීනත්වය සහ ගැඹුරු ස්වයං අවබෝධය",riskEn:"feeling unsupported or withdrawing under pressure",riskSi:"සහාය නොමැති බව දැනීම හෝ පීඩනයේදී ඉවත් වීම",actionEn:"Build reliable routines and ask for support early",actionSi:"විශ්වාසදායක දෛනික රටා ගොඩනඟා ඉක්මනින් සහාය ඉල්ලන්න"},
};
const G:YogaMeaning={lifeEn:"the areas governed by its forming planets and houses",lifeSi:"එය සාදන ග්‍රහයන් සහ භාවයන් පාලනය කරන ජීවන අංශ",giftEn:"useful potential that grows when its planets are supported",giftSi:"එහි ග්‍රහයන්ට සහාය ලැබෙන විට වර්ධනය වන ප්‍රයෝජනවත් හැකියාව",riskEn:"treating it as an automatic promise without checking strength and timing",riskSi:"බලය සහ කාලය නොබලා එය ස්වයංක්‍රීය පොරොන්දුවක් ලෙස ගැනීම",actionEn:"Develop the related skills and use favourable periods deliberately",actionSi:"අදාළ හැකියාවන් වර්ධනය කර හිතකර කාල සවිඥානිකව භාවිත කරන්න"};
const level=(n:number,l:Language)=>l==="si"?(n>=80?"ප්‍රධාන බලයක්":n>=65?"බලවත්":n>=50?"මධ්‍යම":n>=35?"සීමිත":"දුර්වල"):(n>=80?"Major influence":n>=65?"Strong":n>=50?"Moderate":n>=35?"Limited":"Weak");
const activeNames=(c:VedicChart)=>[c.dasha.currentMaha?.lordEn,c.dasha.currentAntar?.lordEn,c.dasha.currentPratyantar?.lordEn];

export function explainPlanet(chart:VedicChart,p:ChartPlanet,l:Language){const m=P[p.key],supported=p.dignity==="exalted"||p.dignity==="own"||p.strength>=65,pressured=p.dignity==="debilitated"||p.combust||p.strength<45,active=activeNames(chart).includes(p.nameEn);return {level:level(p.strength,l),meaning:l==="si"?`${p.nameSi} ${p.signSi} රාශියේ ${p.house} වන භාවයේ පිහිටීම ${m.si} ඔබේ ජීවිතයේ ප්‍රකාශ වන ආකාරය පෙන්වයි. මෙය නියත සිදුවීමක් නොව නැවත නැවත ක්‍රියා කරන ප්‍රවණතාවයකි.`:`${p.nameEn} in ${p.signEn}, House ${p.house}, shows how ${m.en} tend to operate in your life. It is a repeating tendency, not a guaranteed event.`,gift:l==="si"?m.giftSi:m.giftEn,risk:l==="si"?m.riskSi:m.riskEn,balance:l==="si"?(supported?"මෙම ග්‍රහයාට හොඳ සහායක් ඇත. එහි බලය වගකීමෙන් භාවිත කළ විට ප්‍රතිඵල ස්ථාවර වේ.":pressured?"මෙම ග්‍රහයා පීඩනය යටතේ ඇත. හැකියාව නැති නොවෙයි; සමබරතාව සහ පුහුණුව වැඩියෙන් අවශ්‍ය වේ.":"හොඳ සහ අභියෝගාත්මක පැති දෙකම ඇත. පුරුදු සහ තීරණ අවසාන ප්‍රතිඵලය වෙනස් කරයි."):(supported?"This planet is well supported. Its benefits become steadier when used responsibly.":pressured?"This planet is under pressure. Its potential remains, but conscious practice and balance matter more.":"Support and pressure are mixed. Habits and choices strongly influence its final expression."),action:l==="si"?m.actionSi:m.actionEn,timing:l==="si"?(active?`${p.nameSi} දැනට දශා මට්ටමක සක්‍රිය බැවින් මෙම කරුණු දැන් වැඩි වැදගත්කමක් ගනී.`:`${p.nameSi} මහා දශා, අතුරු දශා හෝ බලවත් ගෝචරවලදී මෙම බලපෑම වඩා පැහැදිලි වේ.`):(active?`${p.nameEn} is active in the current dasha sequence, so these themes deserve extra attention now.`:`This influence becomes clearer during ${p.nameEn} mahadasha, antardasha or strong transits.`)};}

export function explainYoga(chart:VedicChart,y:ChartYoga,l:Language){const m=Y[y.key]||G,active=y.planets.some(n=>activeNames(chart).includes(n));return {level:level(y.power,l),meaning:l==="si"?`මෙම යෝගය ප්‍රධාන වශයෙන් ${m.lifeSi} කෙරෙහි බලපායි. ${y.power}/100 බලය අනුව එය හැකියාවක් ලෙස ඇත; සෑම කාලයකම එකම ලෙස ක්‍රියා නොකරයි.`:`This yoga mainly influences ${m.lifeEn}. At ${y.power}/100 it is a chart potential, but it will not operate equally at all times.`,gift:l==="si"?m.giftSi:m.giftEn,risk:l==="si"?m.riskSi:m.riskEn,action:l==="si"?m.actionSi:m.actionEn,timing:l==="si"?(active?"යෝගය සාදන ග්‍රහයෙකු දැනට දශාවක සක්‍රිය බැවින් එය දැන් වැඩි අවධානයක් ඉල්ලා සිටිය හැක.":"එය සාදන ග්‍රහයන්ගේ දශා, අතුරු දශා සහ හිතකර ගෝචරවලදී වඩා ක්‍රියාත්මක විය හැක."):(active?"A forming planet is active in the current dasha sequence, making this yoga more relevant now.":"It is more likely to activate during its planets’ dashas, antardashas and supportive transits.")};}
